### PR TITLE
support source maps

### PR DESCRIPTION
**Pull request by Liiioooo**

### CODE REVIEW

**Comment by afterwind-io** [comment]
@Liiioooo 
It seems you would like to transparently pass some source map from upstream to the next loader. 

- The preprocessor is designed to deal with raw code directly. Theoretically there should be no loader before the preprocessor, thus no source map from upstream. So I am a little curious about your actual scenario.

- Certain lines of code would likely be cut during preprocessing, and it can leads to potential problems. If source map generated from upstream does exist, it does not "know" the fact that some code will be trimmed afterwards, because the source map itself is based on the processed code from last step. In conclusion, the mapping would be broken and it will create offset after the *cuts*.

**Comment by Liiioooo** [comment]
I am using the Angular CLI and extended the webpack config, the preprocessor-loader is the first one used. I had to make these changes to your loader, because, without them I got offsets in my mapped Source Code.

**Comment by afterwind-io** [comment]
> ... the preprocessor-loader is the **first** one used...

Sorry I'm not familiar with Angular CLI and its configs. I just searched on the net and found this:
https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#custom-webpack-config-object

It seems some kind of partial Webpack config can be used to override the default Angular inner configs. Is the "first" here means something like:

```javascript
// ...
{
  test: /\.ts$/,
  use: [
    // Other loaders...
    {loader: 'webpack-preprocessor-loader', options: {...}},
  ]
}
// ...
```

**OR**

```javascript
// ...
{
  test: /\.ts$/,
  use: [
    {loader: 'webpack-preprocessor-loader', options: {...}},
    // Other loaders...
  ]
}
// ...
```

If your case is similar to the second one, consider moving it to the last of the loader array?

p.s. I am quite confused right now. Would you please consider sharing your `angular.json` or anything contains this certain part of the config?

**Comment by Liiioooo** [comment]
I am currently using a config simular to tthe second example, because, somehow it doesn't work at all when I use the loader at the end of the array.

**Comment by afterwind-io** [comment]
@Liiioooo 
I created a new angular project by cli, tested a bit and read some source code of the official loader, only to find appending `preprocessor` simply does not work. Explanations and details are referenced above in Issue 7.

Also, passing source map downwards does not help solving the problems neither. As expected, mapping offsets still exists. If you don't bother with losing partial source map (the js-to-ts part), you can just set `mergeStrategies` to `prepend` and let it go. It is not perfect, but the mapping works properly.

**Comment by afterwind-io** [comment]
Closed due to inactivity.

**Pull request closed without merging**
